name: Tests

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  linux:
    name: ${{ matrix.PLATFORM }} py${{ matrix.PYTHON_VERSION }}
    runs-on: ${{ matrix.PLATFORM }}-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CODECOV_TOKEN: e025254a-fe54-4914-8890-0c26e7aa0d07
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6', '3.9', 'pypy3']
        PLATFORM: ['ubuntu', 'macos',  'windows']
        exclude:
        - PLATFORM: windows
          PYTHON_VERSION: pypy3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('etc/example-environment.yml') }}
      - name: Setup conda ${{ matrix.PYTHON_VERSION }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          conda install setuptools pip wheel
      - name: Install pywin32 on Windows
        if: ${{ runner.os == 'Windows' }}
        run: conda install pywin32
      - name: Install project dependencies
        run: |
          pip install -v -e ".[test]" --cache-dir ~/.cache/pip
      - run: conda info
      - run: conda list
      - run: conda config --show
      - run: pip check
      - name: Run python tests
        # See `setup.cfg` for full test options
        run: |
          pytest --pyargs jupyterlab_server
      - name: Upload coverage
        run: |
          codecov
      - name: Install and Test SDist
        if: ${{ runner.os != 'Windows' }}
        run: |
          set -eux
          pip uninstall -y jupyterlab_server
          python setup.py sdist
          cd dist
          pip install *.tar.gz
          pytest --pyargs jupyterlab_server
      - name: Build docs
        run: |
          set -eux
          pushd docs
          conda env create -f environment.yml
          conda activate jupyterlab_server_documentation
          pip install ..
          make html
          conda deactivate
          popd
