name: Tests

on: [push, pull_request]

jobs:
  linux:
    name: ${{ matrix.PLATFORM }} py${{ matrix.PYTHON_VERSION }}
    runs-on: ${{ matrix.PLATFORM }}-latest
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CODECOV_TOKEN: e025254a-fe54-4914-8890-0c26e7aa0d07
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6', '3.9', 'pypy3']
        PLATFORM: ['ubuntu', 'macos',  'windows']
        exclude:
        - PLATFORM: windows
          PYTHON_VERSION: pypy3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup python ${{ matrix.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          architecture: 'x64'
      - name: Install python dependencies
        run: |
          pip install setuptools pip wheel --upgrade --user --cache-dir ~/.cache/pip
      - name: Install project dependencies
        run: |
          pip install -v -e ".[test]" --cache-dir ~/.cache/pip
      - name: Show python environment
        run: |
          python --version
          python -m pip freeze
          python -m pip check
      - name: Run python tests
        # See `setup.cfg` for full test options
        run: |
          pytest
      - name: Upload coverage
        run: |
          codecov
      - name: Install and Test SDist
        if: ${{ runner.os != 'Windows' }}
        run: |
          pip uninstall -y jupyterlab_server
          python setup.py sdist
          cd dist
          pip install *.tar.gz
          pytest --pyargs jupyterlab_server